import PDFDocument from "pdfkit";
import { putObject, getPublicImageUrl } from "./s3";

export interface ReceiptData {
  paymentId: number;
  amount: number; // in cents
  currency: string;
  date: Date;
  description: string;
  tenantName: string;
  landlordName: string;
  propertyTitle: string;
  propertyAddress: string;
  paymentMethod: string;
  reference?: string;
}

export async function generateReceiptPdf(data: ReceiptData): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A5", margin: 50 }); // A5 is good for receipts
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", async () => {
        try {
          const pdfBuffer = Buffer.concat(chunks);
          const fileKey = `receipts/receipt-${data.paymentId}-${Date.now()}.pdf`;
          
          // Upload to S3
          await putObject(fileKey, pdfBuffer, "application/pdf", "public-read");
          
          const url = getPublicImageUrl(fileKey);
          resolve(url);
        } catch (error) {
          reject(error);
        }
      });

      // --- Receipt Design ---

      // Header
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("PAYMENT RECEIPT", { align: "center" })
        .moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text("ClearLet Platform", { align: "center", color: "grey" })
        .moveDown(2);

      // Amount Box
      doc
        .rect(50, doc.y, doc.page.width - 100, 60)
        .fillAndStroke("#f0fdf4", "#16a34a"); // Light green bg, green border
      
      const amountY = doc.y;
      
      doc
        .fillColor("#166534") // Dark green text
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(
          `${(data.amount / 100).toFixed(2)} ${data.currency}`,
          50,
          amountY + 20,
          { align: "center", width: doc.page.width - 100 }
        );

      doc.moveDown(4);
      doc.fillColor("black");

      // Details Table
      const leftColX = 50;
      const rightColX = 180;
      const lineHeight = 20;
      let currentY = doc.y;

      const drawRow = (label: string, value: string) => {
        doc.fontSize(10).font("Helvetica-Bold").text(label, leftColX, currentY);
        doc.font("Helvetica").text(value, rightColX, currentY);
        currentY += lineHeight;
      };

      drawRow("Receipt ID:", `#${data.paymentId}`);
      drawRow("Date Paid:", data.date.toLocaleDateString());
      drawRow("Payment Method:", data.paymentMethod || "Online");
      if (data.reference) drawRow("Reference:", data.reference);
      
      currentY += 10; // Spacer

      drawRow("Property:", data.propertyTitle);
      drawRow("Address:", data.propertyAddress);
      
      currentY += 10; // Spacer

      drawRow("Tenant (Payer):", data.tenantName);
      drawRow("Landlord (Payee):", data.landlordName);
      
      currentY += 10; // Spacer

      drawRow("Description:", data.description);

      // Footer
      doc
        .moveDown(4)
        .fontSize(8)
        .font("Helvetica-Oblique")
        .text("This receipt was automatically generated by ClearLet.", { align: "center", color: "grey" });

      doc.end();

    } catch (error) {
      reject(error);
    }
  });
}
